// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetRedLineAG.Data;

namespace ProjetRedLineAG.Migrations
{
    [DbContext(typeof(ApplicationsContext))]
    [Migration("20220719075830_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetRedLineAG.Models.ApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentsApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("EntrepriseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalLinkApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeApplication")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleApplication")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ProjetRedLineAG.Models.DocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TitleDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ProjetRedLineAG.Models.EntrepriseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentsEntreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailEntreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkEntreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelEntreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEntreprise")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("ProjetRedLineAG.Models.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentsPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("FirstNamePerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNamePerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
